version: 2

jobs:
  build:
    working_directory: /go/src/github.com/toghrulmaharramov/dusk-go
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout

    - run: go get -v -d -t ./...
    - run: go vet ./...
    - run: go test -v -race ./...