# noded config file (TOML).
# Notes:
#   Keys are case insensitive.
#   Nesting is fine, but not necessary.

# Env.net and seeds are the only mandatory config vars.
# Env.net can also be set by:
# - environment variable 'DUSK.ENV.NET'
# - commandline argument 'env.net'
[Env]
net = "DevNet"

[DevNet]
    magic = 1953721920 # Selfmade magic. Used decimal as toml doesn't understand hex. Consider using yaml.

    [DevNet.logging]
    # Default log filepath is <user home>/.dusk/<env.net>/noded/noded.log
    #filepath = "D:/temp/.dusk/dev/noded/noded.log"
    # Default log level is info (log levels: trace, debug, info, warning, error, fatal and panic)
    level = "debug"
    # Default log date format is 2006-01-02 15:04:05 (See: https://golang.org/src/time/format.go)
    #timestampFormat = "2006-01-02 15:04:05"
    # Write log file for a TTY device (to see coloured log text). Default is false
    #tty = true

    [DevNet.peer]
    # Default port is 10333 #TODO: Discuss this
    #port =
    # Default dialTimeout is 0
    #dialTimeout =
    seeds = [ "192.168.178.57:10111" ]
    min = 3
    max = 10
    minGetAddr = 5

    [DevNet.monitoring]
    # Disable events for a certain time to be triggered again. Default is 1 minute.
    #evtDisableDuration = "2m"

    [DevNet.database]
    # Default is <user home>/.dusk/<env.net>/db
    #dirpath = "D:/temp/.dusk/dev/bcdb"


[TestNet]

    [TestNet.logging]
    # Default log filepath is <user home>/.dusk/noded/noded.log
    filepath = "D:/temp/.dusk/test/noded/noded.log"
    # Default log level is info (log levels: trace, debug, info, warning, error, fatal and panic)
    level = "info"
    # Default log date format is 2006-01-02 15:04:05
    dateformat = "2006-01-02 15:04:05"
    # Default log format is [%lvl%]: %time% - %msg%
    format = "[%lvl%]: %time% - %msg%"

    [TestNet.peer]
    seeds = [ "192.168.178.57:10111", "192.168.178.57:10222" ]

    [TestNet.monitoring]
    # Disable events for a certain time to be triggered again. Default is 1 minute.
    evtDisableDuration = "2m"

    [TestNet.database]
    dirpath = "D:/temp/.dusk/test/bcdb"


[MainNet]

    [MainNet.logging]
    # Default log filepath is <user home>/.dusk/noded/noded.log
    filepath = "D:/temp/.dusk/main/noded/noded.log"
    # Default log level is info (log levels: trace, debug, info, warning, error, fatal and panic)
    level = "error"
    # Default log date format is 2006-01-02 15:04:05
    dateformat = "2006-01-02 15:04:05"
    # Default log format is [%lvl%]: %time% - %msg%
    format = "[%lvl%]: %time% - %msg%"

    [MainNet.peer]
    seeds = [ "192.168.178.57:10111", "192.168.178.57:10222" ]

    [MainNet.database]
    dirpath = "D:/temp/.dusk/main/bcdb"
